### ISSUE TITLE
Add ".nvmrc" file for webapp.

### ISSUE THREAD

**Issue by avas27JTG** [mattermost/mattermost-plugin-starter-template#168]
It becomes difficult sometimes to use the proper node version for installing the web app dependencies on the hit and trial method as the `.nvmrc` file is missing. Please let me know if I should create one PR for it, for me the node version that worked correctly was `14.18.0`.

**Comment by hanzei** [comment]
@avas27JTG That would be great!

**Comment by ecator** [comment]
I was the v14.21.2, but npm didn't work, I used yarn. And there are many other problems such as `make check-style` and `make test` doesn't work. Fortunately the `make dist` and `make deploy` is ok  😺 

I think using the [Docker Dev Environments ](https://docs.docker.com/desktop/dev-environments/) will be better. The go and node version can be fixed in container.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-starter-template/pull/173

**Comment by hanzei** [comment]
@ecator Since https://github.com/mattermost/mattermost-plugin-starter-template/pull/163 got merge, node `16.12` is used. Plase open a new issue if you are having issues with that version.
